[package]
name = "valkyrie-parser"
version = "0.2.2"
authors = ["192608617@qq.com"]
edition = "2018"
description = "The hand write parser of valkyrie language"
documentation = "https://github.com/nyar-vm/valkyrie.rs"
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"

[dependencies]
pratt = "0.4.0"
bit-set = "0.5.3"

[dependencies.pex]
version = "0.1.16"
features = ["regex"]

[dependencies.lispify]
version = "0.0.1"

[dependencies.valkyrie-ast]
version = "0.0.*"
features = ["pretty-print", "std"]
path = "../valkyrie-ast"

[dependencies.valkyrie-error]
path = "../valkyrie-errors"
features = []
version = "0.1.*"

[dev-dependencies]


[build-dependencies]
