[package]
name = "valkyrie-parser"
version = "0.2.1"
authors = ["192608617@qq.com"]
edition = "2018"
description = "The hand write parser of valkyrie language"
documentation = "https://github.com/nyar-vm/valkyrie.rs"
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"

[dependencies]
pratt = "0.4.0"
bit-set = "0.5.3"
regex = "1.8.1"
pex = { version = "0.1.7", features = ["regex"]}
# lazy_static = "1.4"

#[dependencies.valkyrie-pest]
#path = "../valkyrie-pest"
#version = "0.2"
#
#[dependencies.nyar-hir]
#path = "../nyar-hir"
#version = "0.2"

[dev-dependencies]


[build-dependencies]
