[package]
name = "valkyrie-parser"
version = "0.2.1"
authors = ["192608617@qq.com"]
edition = "2018"
description = "The hand write parser of valkyrie language"
documentation = "https://github.com/nyar-vm/valkyrie.rs"
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"

[dependencies]
bit-set = "0.5.3"

[dependencies.lispify]
version = "0.0.1"
#path = "D:\\Java\\pex-sexpr\\projects\\sexpr"

[dependencies.valkyrie-ast]
version = "0.0.*"
features = ["pretty-print", "std"]
path = "../valkyrie-ast"

[dependencies.valkyrie-types]
version = "0.0.*"
features = ["pex", "pratt"]
path = "../valkyrie-types"

#[dependencies.valkyrie-error]
#path = "../valkyrie-errors"
#version = "0.0.*"

#
#[dependencies.nyar-hir]
#path = "../nyar-hir"
#version = "0.2"

[dev-dependencies]


[build-dependencies]
