[package]
name = "valkyrie-parser"
version = "0.2.1"
authors = ["192608617@qq.com"]
edition = "2018"
description = "The hand write parser of valkyrie language"
documentation = "https://github.com/nyar-vm/valkyrie.rs"
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"

[dependencies]
syntax-error = "0.0.2"
url = "2.3.1"
pratt = "0.4.0"
bit-set = "0.5.3"

[dependencies.lispify]
version = "0.0.1"
#path = "D:\\Java\\pex-sexpr\\projects\\sexpr"

[dependencies.valkyrie-ast]
version = "0.0.2"
features = []
path = "../valkyrie-ast"

[dependencies.valkyrie-types]
version = "0.0.1"
features = ["pex"]
path = "../valkyrie-types"

#[dependencies.valkyrie-pest]
#path = "../valkyrie-pest"
#version = "0.2"
#
#[dependencies.nyar-hir]
#path = "../nyar-hir"
#version = "0.2"

[dev-dependencies]


[build-dependencies]
