[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/valkyrie-ast",
    "projects/valkyrie-hir",
    "projects/valkyrie-parser",
    "projects/valkyrie-types",
]
exclude = [

]

[profile.release]
lto = true
opt-level = "s"


[workspace.dependencies.nyar-error]
version = "0.1.17"
features = ["json5", "num", "dashu", "walkdir", "pratt", "yggdrasil-rt"]
#path = 'C:\Users\Dell\CLionProjects\nyar-vm\projects\nyar-error'

[workspace.dependencies.nyar-wasm]
version = "0.0.7"
#git = "https://github.com/nyar-vm/nyar-vm.git"
#branch = "dev"
path = 'E:\RustroverProjects\nyar-vm\projects\nyar-wasm'