[workspace]

members = ["projects/*"]
default-members = [
    "projects/valkyrie-parser",
]
exclude = [
    "projects/valkyrie-core",
#   "projects/valkyrie-std",
]

[profile.release]
lto = true
opt-level = "s"