[workspace]
members = ["projects/*"]
default-members = [
    "projects/valkyrie-ast",
    #    "projects/nyar-mir",
    #    "projects/nyar-error",
    #    "projects/valkyrie-parser",
    #    "projects/valkyrie-errors",
]
exclude = [

]

[profile.release]
lto = true
opt-level = "s"