[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/valkyrie-ast",
    "projects/valkyrie-parser",
    "projects/valkyrie-types",
]
exclude = [

]

[profile.release]
lto = true
opt-level = "s"


[workspace.dependencies.nyar-error]
version = "0.1.14"
features = ["json5", "num", "dashu", "walkdir", "pratt", "yggdrasil-rt"]
#path = 'C:\Users\Dell\CLionProjects\nyar-vm\projects\nyar-error'