[package]
name = "valkyrie-types"
version = "0.0.5"
authors = ["Aster <192607617@qq.com>"]
description = "Shard types for valkyrie language"
repository = "https://github.com/nyar-vm/valkyrie.rs"
documentation = "https://docs.rs/valkyrie-types"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
serde = "1.0.163"
patricia_tree = "0.5.7"
dashu = { version = "0.3.1", features = ["serde"] }
num-traits = "0.2.15"
indexmap = "1.9.2"
inwelling = "0.5.0"
itertools = "0.10.5"
image = { version = "0.24.6", features = [] }
ndarray = { version = "0.15.6", features = [] }
polars = { version = "0.30.0", features = ["lazy"], optional = true }

[dependencies.valkyrie-error]
version = "0.1.3"
path = "../valkyrie-errors"
features = ["serde_json", "json5", "dashu"]

[dependencies.valkyrie-ast]
version = "0.1.*"
path = "../valkyrie-ast"

[dev-dependencies]

[features]
default = []
