[package]
name = "valkyrie-types"
version = "0.0.1"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/nyar-vm/valkyrie.rs"
documentation = "https://docs.rs/valkyrie-types"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
num = "0.4.0"
indexmap = "1.9.2"
inwelling = "0.5.0"
itertools = "0.10.5"

pex = { version = "0.1.14", features = ["regex"],  optional = true }

[dev-dependencies]

[features]
default = []
