[package]
name = "valkyrie-ast"
version = "0.0.8"
authors = ["Aster <192607617@qq.com>"]
description = "Strong typed abstract syntax tree of valkyrie language"
repository = "https://github.com/nyar-vm/valkyrie.rs"
documentation = "https://docs.rs/valkyrie-ast"
keywords = ["valkyrie", "ast", "parser", "language"]
categories = ["data-structures"]
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
pretty = "0.12.1"

[dependencies.indentation]
version = "0.1.6"
#path = "C:\\Users\\Dell\\CLionProjects\\pex-sexpr\\projects\\indentation"

[features]
default = []
#serde = ["dep:serde", "url/serde"]
