[package]
name = "valkyrie-ast"
version = "0.0.3"
authors = ["Aster <192607617@qq.com>"]
description = "Abstract Syntax Tree of valkyrie language"
repository = "https://github.com/nyar-vm/valkyrie.rs"
documentation = "https://docs.rs/valkyrie-ast"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
#syntax-error = "0.0.2"
#serde = { version = "1.0.163", features = ["derive"], optional = true }

#[dependencies.valkyrie-types]
#version = "0.0.1"
#path = "../valkyrie-types"
#features = ["url"]

[features]
default = []
#serde = ["dep:serde", "url/serde"]
