[package]
name = "valkyrie-ast"
version = "0.0.9"
authors = ["Aster <192607617@qq.com>"]
description = "Strong typed abstract syntax tree of valkyrie language"
repository = "https://github.com/nyar-vm/valkyrie.rs"
documentation = "https://docs.rs/valkyrie-ast"
keywords = ["valkyrie", "ast", "parser", "language"]
categories = ["data-structures"]
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
#pretty = "0.12.1"

[dependencies.pretty-print]
version = "0.0.0"
path = 'C:\Users\Dell\CLionProjects\pretty-print\projects\pretty-print'
optional = true

[features]
default = ["pretty-print"]
std = ["pretty-print/std"]
#serde = ["dep:serde", "url/serde"]
